from types import TracebackType

class ClientConnection:
    """Sync WebSocket client connection backed by tungstenite."""

    def __init__(
        self,
        url: str,
        connect_timeout: float | None = None,
        receive_timeout: float | None = None,
        tcp_nodelay: bool | None = None,
    ) -> None: ...
    def send(self, message: str | bytes) -> None: ...
    def recv(self) -> str | bytes: ...
    def close(self) -> None: ...
    def ping(self, data: bytes | None = None) -> None: ...
    def pong(self, data: bytes | None = None) -> None: ...

    @property
    def open(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    @property
    def local_address(self) -> tuple[str, int] | None: ...
    @property
    def remote_address(self) -> tuple[str, int] | None: ...
    @property
    def close_code(self) -> int | None: ...
    @property
    def close_reason(self) -> str | None: ...

    def __enter__(self) -> ClientConnection: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_value: BaseException | None = None,
        traceback: TracebackType | None = None,
    ) -> bool: ...
    def __iter__(self) -> ClientConnection: ...
    def __next__(self) -> str | bytes: ...

def connect(uri: str, **kwargs: object) -> ClientConnection:
    """Create a sync WebSocket client connection.

    Args:
        uri: WebSocket server URL (e.g., ``"ws://localhost:8765"``).
        **kwargs: Accepted for compatibility, currently ignored.
    """
    ...
